### ISSUE TITLE
JSON parsing error with Docker 1.7.0

### ISSUE THREAD

**Issue by grkvlt** [projectcalico/calico-docker#261]
I get the following error when using Clocker and trying to create a container using the Docker REST API with Docker 1.7.0 and Calico 0.4.8 installed. There's no extra configuration at this point beyond installing Docker and the calico-node container.

```
Caused by: org.jclouds.http.HttpResponseException:
command: POST http://159.8.142.208:2377/v1.16/containers/create?name=calico_05 HTTP/1.1 failed with response:
HTTP/1.1 500 Internal Server Error; content: [json: cannot unmarshal object into Go value of type []runconfig.DeviceMapping
```

I have worked around this by rolling back my Docker deployment to 1.6.2 for the moment, but it seems to be straightforwardly reproduceable in my environment.

**Comment by tomdee** [comment]
Are you able to repro this without calico installed?

Could you create a diags bundle and send it to us? (either using calicoctl diags, or just zipping up /var/log/calico)

**Comment by robbrockbank** [comment]
Hi Andrew,

Just a quick follow up - did you manage to gather diags as Tom mentioned above?

One thing to note, the most recent release of the calico-docker images uses libnetwork rather than powerstrip (this currently requires use of the experimental Docker release).  See our docs for details.  We've archived off the powerstrip branch.  Would it be worth retrying using the libnetwork release?

**Comment by tomdee** [comment]
Closing as we can't fix without additional diags and this in on an old version of calico. Please reopen if you're still hitting this.
