### ISSUE TITLE
Calling calicoctl from inside a container

### ISSUE THREAD

**Issue by flipchart** [projectcalico/calico-docker#399]
I would like to be able to modify the host calico network from within a container. Is this currently possible? Specifically I want to be able to add/remove calico profiles from other containers. E.g. if there are 2 containers aaa, bbb, then I want to add a profile xxx to container bbb but run the commands from within container aaa

**Comment by tomdee** [comment]
You should be able to add/remove profiles from containers using calicoctl running inside a container. What error are you seeing (and what version are you using)?

The only commands that I can think of that won't work from inside a container are the `calicoctl container` and `calicoctl node` commands.

**Comment by flipchart** [comment]
Ok so I had simply assumed it wouldn't be possible. So I spent some time working through some examples and it seems that I need docker within the container as I need to call `calicoctl container xxx endpoint-id show` to be able to get the endpoint and do the profile append. 

Through my working I happened to actually read the output of `calicoctl` which pointed me to the `ETCD_AUTHORITY` environment variable. Does a variable like this exist for the docker commands? If so, then that could potentially be a solution to the docker requirements.

**Comment by spikecurtis** [comment]
@flipchart the `docker` command will read the `DOCKER_HOST` environment variable to target its connection to the Docker API (also understands `-H` flag on the command line).  But, to be reachable, the your docker daemon either needs to expose its API on a TCP socket, or you have to volume-mount the Docker unix socket into the container.

**Comment by flipchart** [comment]
So to get docker working within the container I had to install it inside the container (not ideal) and then set the variable `DOCKER_HOST`. This gave me access to the host docker environment via docker commands, and also gave me some access to the calico commands all from within the container. The one that didn't work was `calicoctl container xxx endpoint-id show` which gave the output `No endpoint was found for xxx`. This despite `docker ps` showing the container, and `calicoctl endpoint show --detailed` showing the endpoint id. 

For my particular scenario, I'm going to go about this a different way (using ssh commands against the host from within the container), but I am interested in getting this to work natively. What would be great is to expose a REST api from calico-node which could be called from within the container. But obviously that is a larger piece of work to be done, and perhaps useful only to a handful of people.

**Comment by spikecurtis** [comment]
@flipchart what's going on here is that `calicoctl container xxx endpoint-id show` is using your hostname to scope its search for the endpoint.  It's designed this way to be fast, since the container name or ID is scoped to a single host.

Since your container's hostname is not the same as the Docker host's hostname, it fails.

Can you tell us a little more about your use case?

As a work around, you may want to consider interacting directly with the etcd datastore.  Documentation describing this data model is here: http://docs.projectcalico.org/en/latest/etcd-data-model.html

**Comment by robbrockbank** [comment]
@flipchart  Hi, I was wondering how things were progressing related to the problems in this issue.

Did you manage to get the ssh approach working, or use an alternative approach?  Would it be possible to share a little more about the use case - so that we can investigate whether there is something useful we can do to enhance the existing commands?

**Comment by tomdee** [comment]
@flipchart It doesn't sound right that you had to install docker inside the container.
