### ISSUE TITLE
error setting interface .. routes to ..: file exists

### ISSUE THREAD

**Issue by webwurst** [projectcalico/calico-docker#434]
I wrote down my steps to create a playground for `projectcalico` here:
https://gist.github.com/webwurst/f72e522a2f9425f15134

Everything looks fine and pinging within the set up containers works fine too. But when removing one container and recreate it I get this error:

> Error response from daemon: Cannot start container 879d46a80f85b427aed5d5a9eb86862d1b789e97b6792974311cc85bba1b2f67: failed sandbox add: failed to add interface tmp0dd24fd99d4 to sandbox: error setting interface "tmp0dd24fd99d4" routes to ["192.168.107.129/32" "192.168.107.129/32"]: file exists

I tried with docker-latest from last week and from today.

What do I wrong? Where can I check?
Regards!

**Comment by TrimBiggs** [comment]
Hi @webwurst,

Thanks for bringing this to our attention.  I'm looking into it now and I'm able to reproduce the error locally by creating a container, removing it, then trying to recreate the container with the same name.  I'll let you know when I find out more about what's going on here.

**Comment by TrimBiggs** [comment]
I believe I know what the issue is.  It seems to be a problem with Docker's libnetwork plugin being unable to create a container using an interface name that was used by a previously deleted container.  I'll try to find a way around this tomorrow and let you know what I come up with.  

I'll be raising an issue in the docker/libnetwork repo as well that I will link to here.

**Comment by webwurst** [comment]
Thx @TrimBiggs! I am really keen to play around some more with callico som more.

**Comment by TrimBiggs** [comment]
Hi @webwurst,

We have raised a couple of issues with docker and learned a bit more about what is causing the problems: https://github.com/docker/docker/issues/15573 and https://github.com/docker/libnetwork/issues/455.

When the container is first created, an endpoint is created.  When the container is removed, the endpoint still exists and the routes still exist.  When the container is created again, the endpoint still exists and rejects the Calico networking because the route still exists in the endpoint.

You can work around this by running a docker command that removes the endpoint from docker after you have removed the container:
```
docker-latest run --publish-service srvB.net2.calico --name workload-B -tid alpine sh
docker-latest rm -f workload-B
docker service unpublish srvB.net2
docker-latest run --publish-service srvB.net2.calico --name workload-B -tid alpine sh
```
You can view your services by calling `docker service ls`.  You shouldn't see the error anymore if you run `docker service unpublish <NAME.NETWORK>` command on the given service.

Hope this helps!  Let me know how it goes!

**Comment by webwurst** [comment]
Thanks a lot! Works fine for me, I have updated my [gist](https://gist.github.com/webwurst/f72e522a2f9425f15134) accordingly. Now up to some more adventures with promising project calico ;)
