### ISSUE TITLE
Multiple felix logfiles

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-docker#480]
I think the current felix.cfg results in multiple felix logfiles.  There's one generated from stdout/err in /var/log/calico/felix/current and a separate one that felix creates by default at /var/log/calico/felix.log.

**Comment by robbrockbank** [comment]
In libcalico, we do set the LogFilePath to be None, but it doesn't seem to be taking hold.

That said, I think we will still initially log to file because the felix.cfg file is used for start up logging (IIRC).  So perhaps the correct fix is to set the values in felix.cfg, but allow them to be overridden by etcd values.  I don't think this is currently possible though.

**Comment by alexhersh** [comment]
`projectcalico/calico/calico/felix/felix.py` initializes logging to a hardcoded `/var/log/calico/felix.log` path.
The `my_init` of the calico/node image in `projectcalico/calico-docker` starts a `svlogd` process that prints to the `/var/log/calico/felix/current` directory. Two conflicting logging schemas. I'm not even sure if `calicoctl config` correctly affects the logging level of either

**Comment by robbrockbank** [comment]
The calicoctl config is used to modify the severity level of logs output to stdout/stderr.  Unless I'm mistaken svlogd captures and writes out anything Felix outputs to stdout/stderr.

So the calicoctl config *should* adjust the log levels for the log files in /var/log/calico/felix/current.

I think the issue is just that Felix is also writing out to file (which we should have disabled).

@alexhersh - are you seeing something different?

**Comment by tomdee** [comment]
Our current felix.cfg contains
```
[global]
MetadataAddr = None
```

I'll try changing it to

```
[global]
MetadataAddr = None
LogFilePath = None
LogSeverityFile   = None
```
