### ISSUE TITLE
calico-docker doesn't work with gce

### ISSUE THREAD

**Issue by DaveLangridge** [projectcalico/calico-docker#489]
created 2 GCE instances. Used calico-docker from https://github.com/projectcalico/calico-docker/releases/download/v0.5.5/calicoctl. created an ipip pool. The tunnel for this has an MTU of 1480, but the eth0 interface is 1460. Small packets (e.g. pings) work between containers, but qperf bandwidth is 0.

If I change the MTU of the tunnel to 1440 on both sides, all is fine. 

A fix for #488 should fix this as well, but this is probably more urgent.

**Comment by TrimBiggs** [comment]
Hi Dave,

I'm working on a fix for this right now.  I'll link to the PR when it goes up to keep this thread updated.

**Comment by DaveLangridge** [comment]
I assume this will include the docs updates to tell users what to set this to. (e.g. 20 below the interface value). Should also consider changing the default so that it works for GCE.

**Comment by plwhite** [comment]
@TrimBiggs I thought you were fixing issue #488? That's not related to this issue.

This bug is that calico-docker is downloading Felix 0.28, which is too old to work on GCE (you need at least Felix 1.0). That in turn is because (I think) calico-docker 0.5.5 downloads that version. The GCE page doesn't seem to explicitly say that only 0.6.0 works, so it probably should do (assuming that all those versions are correct - it's a bit confusing so feel free to correct me!).

**Comment by DaveLangridge** [comment]
Just to confirm. I upgraded calico-docker to version 0.6.0, and qperf worked fine. This issue can be closed. Though you might want to update the GCE page @plwhite mentioned. (I couldn't find that page - but I didn't look hard.)

**Comment by TrimBiggs** [comment]
Thanks for the clarification.  I'm updating the doc to make it clear that v0.6.0 is required when using GCE.   Following the current instructions of the GCE doc will automatically pull v0.6.0.

It seems that GCE is likely incompatible with Calico's powerstrip networking since the powerstrip release is based calico-docker and felix from several months ago.  We could possibly update this at some point.

**Comment by TrimBiggs** [comment]
The doc is updated with PR #491. Feel free to review and leave any comments!

**Comment by TrimBiggs** [comment]
Fixed by #491
