### ISSUE TITLE
Calico-docker does not work on AWS without VPC

### ISSUE THREAD

**Issue by Graeme-Miller** [projectcalico/calico-docker#490]
Whilst following the instructions [here](https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/AWS.md) I have run into some issues. 

The root cause is that, running Calico on AWS requires your EC2 instances to be running within a VPC. Amazon will not allow ipencap traffic unless it is within a VPC. If this is expected functionality then the documentation should be updated. The instructions ask you to create a security groups as follows:

> \# Allow hosts in the security group to communicate with each other
> aws ec2 authorize-security-group-ingress \
>  --group-name MySG \
>  --protocol all \
>  --port all \
>  --source-group MySG

However, this will return an error, as "protocol all" is forbidden unless you are setting up a group for a VPC.

To get the example to work I had to follow these steps:
* Created VPC
* Created Subnet, with auto-assign public IP on (needed for SSH)
* Updated security rule to allow all traffic (this works because it is for a VPC)
* Created an Internet Gateway, and attached it to VPC (needed for SSH)
* Created a Route Table, attached it to subnet, added route to Internet Gateway (needed for SSH)
* Used the following command to create the instances:
aws ec2 run-instances   --image-id ami-29734819   --instance-type t1.micro   --key-name mykey   --user-data file:///Users/graememiller/Downloads/clocker/manual_attempt/user-data-[first|others] --subnet subnet-21b0da56

**Comment by lxpollitt** [comment]
We should definitely update the docs to resolve this issue, both in terms of making it clear that VPC is required and guiding users through the key VPC setup steps.  I think it is important to have a clear split between "here's how you set up a VPC in general, with SSH etc working" and "here's how you then add Calico".  For the former, we should also point to AWS's instructions.  (If they are concise enough then we might not need to include the steps in our instructions.)

**Comment by TrimBiggs** [comment]
Thanks for the clear steps that you took to set up networking.  I'll update this doc first thing tomorrow.

**Comment by TrimBiggs** [comment]
I've added PR #493, which explains how to create a VPC and associated AWS objects, rather than using the AWS default VPC.  I plan to run through the whole demo again before getting this reviewed/merged.

**Comment by lxpollitt** [comment]
@trimbiggs I'm not clear why you say "rather than using the AWS default VPC"?

**Comment by TrimBiggs** [comment]
@lxpollitt, just did a bit of research on AWS and I think I'm understanding what's going on now.

Accounts created before Dec 4, 2013 support [EC2-Classic and EC2-VPC](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-vpc.html), and all accounts created after just support EC2-VPC.  EC2-Classic does not use VPC; instead it allows instances to run in a single, flat network that you share with other customers. 

When I created my account recently, my AWS used EC2-VPC and had a default VPC that was set up with all of the required objects when it first comes up (VPC, Subnets, Internet Gateway, Route Table).  The demo worked fine just using the default VPC.

We need to be explicit about requiring VPC, rather than using EC2-Classic.  Adding a new VPC could be useful to isolate the containers on calico to their own network, but I don't think it is necessarily required unless the user is on EC2-Classic.

@Graeme-Miller, does this match your understanding?

**Comment by TrimBiggs** [comment]
I've updated this PR, which covers creating a VPC if no default VPC is available: #493

**Comment by TrimBiggs** [comment]
Fixed by #493
