### ISSUE TITLE
"curl: symbol lookup error" when running `calicoctl diags`

### ISSUE THREAD

**Issue by Symmetric** [projectcalico/calico-docker#60]
Using the calico-coreos-vagrant-example template, I'm getting the following error when running `calicoctl diags`:

```
core@core-02 ~ $ sudo ./calicoctl diags
Collecting diags
Using temp dir: /tmp/tmp.DgXsHLiLFl
Dumping netstat output
Dumping routes
Dumping iptables
Copying Calico logs
Dumping datastore
curl: symbol lookup error: /lib64/libcurl.so.4: undefined symbol: SSLv2_client_method
Diags saved to diags-20150413_223645.tar.gz in /tmp/tmp.DgXsHLiLFl
Uploading file. Available for 14 days from the URL printed when the upload completes
curl: symbol lookup error: /lib64/libcurl.so.4: undefined symbol: SSLv2_client_method
Done
```

This is with v0.3.1, running CoreOS v575.0.0.

**Comment by neiljerram** [comment]
I've seen something like that, except with SSLv3 instead of v2, and with gevent instead of curl. The reason was that the OpenSSL on the host OS (Debian) did not provide the SSLv3 symbol, because they had removed it (cf. upstream OpenSSL) on the grounds of it being insecure. Fix was to install a newer gevent (from git) that doesn't ask for SSLv3.Could it be similar in your case?

**Comment by neiljerram** [comment]
I've just had a similar report from another partner, and it now appears that my previous comment was probably entirely irrelevant.  Instead, these errors seem to be to do with how the binary version of calicoctl is prepared (from the calicoctl.py source).  It appears that the binary version can assume that certain libraries or features will be present on the system where calicoctl is run - and then in fact they might not be.

In the new case that I just heard about, the lookup error was from 'sh' trying to lookup 'rl_signal_event_hook', and it occurred when running 'calicoctl node ...'.

**Comment by neiljerram** [comment]
Similar problems are being discussed here: https://github.com/docker/compose/issues/170.

Also note that the 'rl_signal_event_hook' report came from running on ArchLinux.

**Comment by neiljerram** [comment]
Ah, http://www.bay12forums.com/smf/index.php?topic=140966.115;wap2 says (for the same problem in an unrelated tool):

    Apparently there's a known incompatibility between Python 2.7 and readline 6.3; the pre-built executable is using a bundled Python 2.7 interpreter, so if you have the latter installed, that would cause it.

    It looks like Python has been updated to fix it since then, so I'll try to get that version installed for the next build

    A workaround until then is to [...] grab the source code [...] and run it from source [...].

So a workaround for the 'rl_signal_event_hook' problem is to run calicoctl.py from source, instead of the pre-built executable.  I imagine that might work for the curl symbol problem too.

**Comment by teemow** [comment]
I've compiled `calicoctl` in a archlinux container and then it works without `rl_signal_event_hook` errors.

**Comment by tomdee** [comment]
@teemow Does this mean you're unblocked for your upcoming demo? If so, we can look into a more strategic fix for this.

**Comment by robbrockbank** [comment]
Tried to fix this using python libraries to replace curl.  Turns out to be a little more complicated than I'd hoped, so downed tools for the time being.

Details of changes so far (see branch: https://github.com/robbrockbank/calico-docker/tree/issue-60-no-curl-installed )

Namely using `requests`.  This had the add-on effect of requiring the following:
- pyopenssl
- ndg-httpsclient
- pyasn1
- requests[secure]
- build-essentials

A pyinstaller hook to include the requests certificate files.

The master version of PyInstaller (pip install version 2.2 is missing function to allow packages that have a .pth file ... which ndg-httpsclient does).

I'm now getting the following:
```
  File "/code/build/calicoctl/out00-PYZ.pyz/cryptography.hazmat.bindings.openssl.binding", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 416, in load_module
    module.__dict__['__file__'] = filename
ImportError: No module named _cffi_backend
```

**Comment by tomdee** [comment]
How about we just remove the upload functionality? And instead print a message saying "You can upload the diagnostic bundle to a file sharing service such as transfer.sh using curl
curl --upload-file XXX https://transfer.sh/XXX"
