### ISSUE TITLE
Calico with libnetwork not support Profile rules?

### ISSUE THREAD

**Issue by frostynova** [projectcalico/calico-docker#630]
I cannot find any guide to use profile rules with libnetwork

**Comment by frostynova** [comment]
And in this doc, https://github.com/projectcalico/calico-docker/blob/master/docs/calicoctl/profile.md , it says:

> NOTE: The calicoctl profile commands should NOT be used when running Calico with the Docker libnetwork driver. The libnetwork driver manages the security policy for containers.

**Comment by robbrockbank** [comment]
Hi @frostynova - this one is on our radar, but still needs a little thought about how to handle.  It may simply end up being a testing/documentation thing - but we'll keep you posted.

**Comment by robbrockbank** [comment]
@frostynova 

We've just release v0.12.0 which adds Calico IPAM support.  One upshot of this is that provided you are using Calico IPAM then it should be possible to edit the profile rules rather than using the default behavior.

We do still need to do a better job of documenting this - or possibly thinking about new commands, or new docker network options to improve this.  I'll close this issue and raise a new one for that side of things.

In the meantime, we do now touch on the manipulation of profiles and endpoints in the libnetwork demonstration.
