### ISSUE TITLE
containers on hosts with different subnet

### ISSUE THREAD

**Issue by AdoHe** [projectcalico/calico-docker#631]
FYI. I have two hosts and they are within different subnet, now I want to use calico to configure the network between containers which running on these two hosts. whether I have to use the `--ipip` flag? and what this flag mean? use ip in ip to do packet encapsulation?

**Comment by AdoHe** [comment]
@tomdee how about this issue?

**Comment by tomdee** [comment]
Do you have IP connectivity between the two hosts? e.g. can they ping each other? If so, then you have L3 connectivity (but not L2 since they are on different hosts).

When Calico starts sending packets across your network with Calico IPs, the routers on your network need to know how to forward those packets. One way to achieve this is it have your routers peer with the Calico hosts (using BGP) which allows them to know where to forward the Calico packets.

If you are unable to do this (e.g. you're running on AWS or GCE) then you can use the `--ipip` option. This encapsulates the packets so that they can pass through intermediate routers without getting dropped.

Please reopen the issue if that doesn't answer your question.

**Comment by AdoHe** [comment]
@tomdee the two hosts can ping each other, they did have L3 connectivity. for this sentence `One way to achieve this is it have your routers peer with the Calico hosts (using BGP) which allows them to know where to forward the Calico packets` I am not very clear, you mean that we should run `BIRD` on every routers peer for BGP?

**Comment by AdoHe** [comment]
@tomdee the routers peer is the `router` which connects two different subnets?
