### ISSUE TITLE
How to install Net Modules in Ubuntu for Docker, Mesos and Calico setup

### ISSUE THREAD

**Issue by ajaybhatnagar** [projectcalico/calico-docker#646]
Hi 
Instructions on the link provide for rpm install for NetModules.  I have working Ubuntu Mesos/ Marathon (v 0.25)cluster and Calico networking (v0.10.0) with Docker (v1.9.0) containers. I would like to add Calico Netmodule to the slave nodes and run a a docker containers cluster with multiple hosts.

I do not plan to use Vagrant based setup.

Thanks
Ajay

**Comment by djosborne** [comment]
Hi @ajaybhatnagar. 

The setup you've described is our end-goal, but unfortunately not yet supported.

We separately support:
1.) Calico Networking with Docker via Libnetwork
2.) Calico Networking in Mesos for Frameworks Launching Applications via the [Mesos Containerizer](http://mesos.apache.org/documentation/latest/containerizer/). 

However we do not yet support Calico-networked Docker Containers in Mesos, since we do not yet support Calico Networking for the the [Docker Containerizer in Mesos](http://mesos.apache.org/documentation/latest/docker-containerizer/). 

Though one possible solution might be to defer networking from Mesos to libnetwork/Docker as you've described, we feel that would result in Mesos Networking being a bit fragmented, so we are working towards the Docker Containerizer support instead.

**Comment by ajaybhatnagar** [comment]
Thanks for the info. Looking forward to Docker containerizer support.

**Comment by dmytroleonenko** [comment]
+1 for that feature

**Comment by djosborne** [comment]
@ajaybhatnagar @dmytroleonenko We've almost merged some Calico-specific Netmodules installation guides at #667 (specifically the [Manual Mesos + Netmodules](https://github.com/djosborne/calico-docker/blob/mesos-docs-update/docs/mesos/ManualInstallNetmodules.md) one

**Comment by djosborne** [comment]
Also @ajaybhatnagar an update on Mesos/Docker networking: work is being done by Mesos on the Mesos Containerizer to support docker containers (deprecating the Docker Containerizer). Since the Mesos Containerizer uses the new networking in Mesos, Calico should work out of the box. Its currently early stage testing.

**Comment by ajaybhatnagar** [comment]
Thanks. Looking forward to functional release.

**Comment by michaelmonroe** [comment]
djosborne, I see  you have updated the GIT pages with netmodules but the manual compilation is still geared to Centos (rpm based).  As we run mesos + marathon on Ubuntu 14.04, we are still looking to do this.  Can you provide any update/feedback? As a sidenote, Mesos has now gone to 0.28 with Marathon sitting at 0.15.3
