### ISSUE TITLE
How to upgrade calico node safely?

### ISSUE THREAD

**Issue by frostynova** [projectcalico/calico-docker#82]
If i want to upgrade the calico node, can i just stop the old container then pull and create a new one? is it safe to do so? (means not affect current environment, such as missing route rule or  iptables rules)

If i have a cluster, can i do this one by one or just together?

**Comment by Lukasa** [comment]
Hi @frostynova!

Right now we don't support seamless upgrade in calico-docker. The core Calico components do, but in calico-docker if you do that then the current environment absolutely *will* be affected. We're working on adding this functionality as we speak: expect it in the near future.

It would be interesting to know what you're doing with calico-docker and what your time-scales are. If you're planning some kind of test or trial deployment, and seamless upgrade is important to you, we'd like to know what your time frame is so that we can have it ready by the time you need it. Any information you can give us about what you're running on and what your time frame is would be super useful.

**Comment by frostynova** [comment]
@Lukasa We just work on a new PaaS for our company, which is based on docker. Current we are still being early stage. I choose calico-docker as our network solution and doing some testing on it. We plan to deploy the first demo app later this month, and in the middle of the year to make it a production environment.

I wonder how current environment will be affected? i think route table and iptables' rules are all keeped by the kernel. Does one calico-docker restart will affect other hosts in the same cluster? If not, can we upgrade the calico node one by one with the current one being offline?

**Comment by tomdee** [comment]
As @Lukasa says above, this is something we're still working on, but broadly speaking, yes, you should be able to do a rolling upgrade of your calico-nodes. If you take one down then other nodes will need to re-exchange routes with it over BGP when it comes back (if you're not using a route reflector).

**Comment by tomdee** [comment]
Closing as the question has been answered. We still need to improve our docs around upgrades but we're tracking that internally.

**Comment by frostynova** [comment]
I am back :)

Now we want to upgrade our environment (Calico 0.4.9 + Docker 1.6) to the latest release (Calico 0.10.0 + Docker 1.9 + libnetwork). 

If we just let a node offline, upgrade calico & docker on it, then put it online, everything is OK? 
I worried that the new node can not join the old network.

**Comment by tomdee** [comment]
Sorry, missed this as the issue was still closed.

Libnetwork complicates things. Make sure you understand it before you upgrade. As long as you use the calico driver _and_ the calico IPAM then you should be OK.

We're going to be releasing v0.11.0 today or maybe over the weekend, I would recommend holding out for that.

Upgrading should be as simple as you describe but we've not tested that particular upgrade. I don't think there have been any non-back compatible data model upgrades. I would highly recommend upgrading a single node first and testing that well!
